spring:
  application:
    name: zero-downtime-deployment
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  env: ${APP_COLOR:local}
  serverAddress: ${SERVER_ADDRESS:127.0.0.1}

serverName: ${SERVER_NAME:local_server}

app:
  color: ${APP_COLOR:local}